### ISSUE TITLE
Is “Dynasour” misspelled in “Purple Dynasour Matters”?

### ISSUE THREAD

**Issue by YDX-2147483647** [pdm-project/pdm-expansions#8]
https://github.com/pdm-project/pdm-expansions/blob/45b141aaf996b3d0742697d73e77f06657fdfbdf/expansions.txt#L16

Maybe _dinosaur_ / _dynasty_? Or on purple?

_Remark_: This line was introduced in [1f63a9](https://github.com/pdm-project/pdm-expansions/commit/1f63a96e5e5cff40af5744b1d47944b8a74de14f).

**Comment by frostming** [comment]
Yes, PR welcomed
